### ISSUE TITLE
Make to execute local jscs

### ISSUE THREAD

**Issue by roadhump** [SublimeLinter/SublimeLinter-jscs#27]
It would be nice to make plugin to execute locally installed jscs in node_modules. It is possible now by extending plugin class from `NodeLinter`.

**Comment by i-akhmadullin** [comment]
Just tried extending plugin from NodeLinter and could not spot any significant difference in debug output except SublimeLinter stopped checking version.
Linter always calls global jscs from folder `/usr/local/bin/`.

I even checked eslint plugin and saw similar output in debug mode:
`SublimeLinter: eslint: file.js ['/usr/local/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@']`

**Comment by OliverJAsh** [comment]
:+1: ESLint plugin behaves as desired, uses local version instead of global (I don't have a global version installed)

**Comment by levacic** [comment]
This is actually very important, since the jscs version (and therefore the rules to be applied) may differ from project to project (in my case, they do, sometimes significantly). If I come back to a project after a few months, I don't want to have to refactor all of the JS code just to satisfy what my up-to-date globally installed jscs version says - in fact, I'd prefer not to have a globally installed jscs version at all.

Has anyone been able to find any sort of workaround? I guess something naughty like symlinking {{/usr/local/bin/jscs}} to the one in your {{node_modules}} in the project you're currently working on might do the trick - but it seems really awful and don't see a clean solution at the moment.

**Comment by kyrylkov** [comment]
Would be nice to have locally installed `jscs` supported

**Comment by braver** [comment]
We're using the NodeLinter here now, so should work.
